package com.bawei.hujintao.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.hujintao.AdderssBean;

import com.bawei.hujintao.database.AdderssBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adderssBeanDaoConfig;

    private final AdderssBeanDao adderssBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adderssBeanDaoConfig = daoConfigMap.get(AdderssBeanDao.class).clone();
        adderssBeanDaoConfig.initIdentityScope(type);

        adderssBeanDao = new AdderssBeanDao(adderssBeanDaoConfig, this);

        registerDao(AdderssBean.class, adderssBeanDao);
    }
    
    public void clear() {
        adderssBeanDaoConfig.clearIdentityScope();
    }

    public AdderssBeanDao getAdderssBeanDao() {
        return adderssBeanDao;
    }

}
